name = "phase-maker"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "phase-maker"

# Static site configuration for Cloudflare Pages
# The build output directory will be 'dist' from Vite

[[routes]]
pattern = "phasemaker.oliverrobson.tech"
custom_domain = true
